image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo /usr/local/bin/docker-compose up -d
  - sudo sleep 15
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - sudo java -jar -Dspring.datasource.url=jdbc:postgresql://localhost:5432/app ./artifacts/aqa-shop.jar &
  - sudo sleep 15
  - sudo chmod +x gradlew

build_script:
  - sudo ./gradlew test -Dselenide.headless=true -Ddatabase=postgresql --info # запускаем тест, флаг --info позволяет выводить больше информации