version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES-DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  gate-simulator-app:
    build: ./gate-simulator
    image: gate-simulator-app:1.0
    ports:
      - '9999:9999'
